"use client";

import "./globals.css";
import type { Metadata } from "next";
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body className="dark:bg-black">{children}</body>
    </html>
  );
}
